
LIBOBJ+=$(OBJDIR)/md5asm.o $(OBJDIR)/__aeabi_unwind_cpp.o
LIBOBJ+=$(OBJDIR)/__fadvise.o $(OBJDIR)/arm_fadvise.o
CFLAGS+=-Os -fomit-frame-pointer -fstrict-aliasing
CFLAGS+=-mcpu=arm7tdmi -mfloat-abi=soft -marm
VPATH:=arm:syscalls.s:$(VPATH)
LIBGMON_OBJS+=$(OBJDIR)/mcount.o
